---
- name: Import Docker CE repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Remove Existing Docker Components
  yum: 
    name: "{{ el_docker_ce_packages_to_remove }}"
    state: absent

- name: Install Docker CE prerequisite  
  yum:
    name: "{{ el_docker_ce_prerequisites }}"
    state: present

- name: Install Docker CE
  yum:
    name: docker-ce
    state: present
    update_cache: yes

- name: Ensure Docker is started and enabled on boot.
  service: name=docker state=started enabled=yes

# Create and managed the /etc/docker/daemon.json
- name: Create etc docker directory
  file:
    path: /etc/docker/
    state: directory
  when: (insecure_registries is defined) 

- name: Configure daemon.json
  template: 
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: (insecure_registries is defined) 
  notify: restart docker

# Create or remove the docker service proxy tower_settings
# If the proxy settings are present, create the files, other wise remove them 
- name: Delete the Docker Service Directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: absent
  when: (http_proxy is undefined) and (https_proxy is undefined)
  notify: restart docker

- name: Create the Docker Service Directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
  when: (http_proxy is defined) or (https_proxy is defined)
  notify: restart docker

- name: Configure HTTP Proxy File when defined 
  template: 
    src: http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart docker
  when: http_proxy is defined

- name: Remove Configure HTTP Proxy File when not defined
  file: 
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: absent
  notify: restart docker
  when: http_proxy is undefined

- name: Configure HTTPS Proxy File when defined
  template: 
    src: https-proxy.conf
    dest: /etc/systemd/system/docker.service.d/https-proxy.conf
  notify: restart docker
  when: https_proxy is defined

- name: Configure HTTPS Proxy File when not defined
  file: 
    path: /etc/systemd/system/docker.service.d/https-proxy.conf
    state: absent
  notify: restart docker
  when: https_proxy is undefined

# - name: Install Docker Compose 
- name: Install Docker Compose
  block:
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755 
    
    - name: Symbolic Link for Docker Compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Register Docker Compose Version
      shell: docker-compose version
      register: docker_version
    
    - debug:
        msg: Docker Version is {{ docker_version }}
  when: docker_compose_version is defined






