---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "docker"
  
  vars:
    http_proxy: http://proxy.lab.home/
    https_proxy: http://proxy.lab.home:8080/
    no_proxy: "*.dan.com,starwars.com"
    docker_compose_version: "1.27.4"

    # insecure_registries: []
      # - abc.net:8080
      # - test.com:5000
      # - fairlady.com:8081