---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "docker"
  
  vars:
    test: test
    configure_http_proxy: 
    configure_https_proxy: 

    # docker_insecure_registries:
    #   - abc.net:8080
    #   - test.com:5000
    #   - fairlady.com:8081